version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: gathering debugging information
          command: |
            whoami
            uname -a
            cat /etc/issue
            cat /proc/1/cgroup
            pwd
            ls -l
            docker info
