version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: gathering debugging information
          command: |
            set -x
            whoami
            uname -a
            cat /etc/issue
            cat /proc/1/cgroup
            pwd
            ls -l
            docker info

      - run:
          name: build dev container
          command: docker build -t reverser-dev .

      - run:
          name: build prod container
          command: |
            docker cp $(docker create reverser-dev):/go/bin/reverser .
            docker build -f Dockerfile.prod -t reverser-prod .
            if [ $(docker run reverser-prod hello) != olleh ]; then exit 1; fi;

      - run:
          name: test dev container
          command: docker run --entrypoint=go reverser-dev test -tags="fast pure" -v github.com/lilylambda/reverser