version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: gathering debugging information
          command: |
            set -x
            whoami
            uname -a
            cat /etc/issue
            cat /proc/1/cgroup
            pwd
            ls -l
            docker info

      - run:
          name: build dev container
          command: docker build -t reverser-dev .

      - run:
          name: log into dockerhub.com
          command: docker login -u $DOCKER_UNAME -p $DOCKER_PASSWORD # these variables are added via the CircleCI UI

      - run:
          name: push dev container
          command: |
            set -x
            DEV_CONTAINER=lilylambda/reverser:${CIRCLE_SHA1}-dev
            docker tag reverser-dev $DEV_CONTAINER
            docker push $DEV_CONTAINER

      - run:
          name: build prod container
          command: |
            set -x
            docker cp $(docker create reverser-dev):/go/bin/reverser .
            docker build -f Dockerfile.prod -t reverser-prod .
            if [ $(docker run reverser-prod hello) != olleh ]; then exit 1; fi;

      - run:
          name: push prod container
          command: |
            set -x
            PROD_CONTAINER=lilylambda/reverser:${CIRCLE_SHA1}-prod
            docker tag reverser-prod $PROD_CONTAINER
            docker push $PROD_CONTAINER

      - run:
          name: test dev container
          command: |
            ID=$(docker create --entrypoint=go reverser-dev test -tags="fast pure" -v github.com/lilylambda/reverser -coverprofile=coverage.txt)
            docker start -a $ID
            docker cp $ID:/go/src/github.com/lilylambda/reverser/coverage.txt .
            ls -l
            cat coverage.txt
            bash <(curl -s https://codecov.io/bash)

